### ISSUE TITLE
Send Email with Attachment

### ISSUE THREAD

**Issue by darryllane** [Narcolapser/python-o365#41] opened 2016-11-03 15:41 UTC
Im getting a False response from `m.sendMessage()` when using attachments and I have no idea why. The `print` statement returns `False` when the following lines are removed it sends fine;

```
att = Attachment(path=filepath)
m.attachments.append(att)
```

example function

```
def email_message(username, password, dir_path):
	try:
		filepath = dir_path + '/filename_{}.csv'.format(str(now))
		authenticiation = (username, password)
		m = Message(auth=authenticiation)
		att = Attachment(path=filepath)
		m.attachments.append(att)
		m.setRecipients("emailhere@address.com")
		m.setSubject("Subject")
		m.setBody("Testing")
		sent = m.sendMessage()
		print sent

	except Exception, e:
		traceback.print_exc()
		print 'Sending Email Failed'
		print e
		return False

	return sent
```

**Comment by Narcolapser** [comment] 2016-11-07 15:04
I've recreated the error. Thank you for pointing it out.

**Comment by Narcolapser** [comment] 2016-11-07 15:17
Ok. this just got strange. The problem I've found is a problem with python 3. You are clearly using python 2. Can you post the relevant contents of O365.log?

**Comment by sampellino** [comment] 2016-11-08 17:43
I'm getting the same thing using Python 2.7.11.

Where does the log file live? I tried searching in my python project's directory and in C:\Python27, and it doesn't show up in either.

I ran an exec on the filepath I'm using, and the image I'm trying to attach opens, so I'm certain the path is valid.

**Comment by sampellino** [comment] 2016-11-08 17:57
I printed my message's `json` contents to the screen after creating it with: body, subject, to, and from. 

There is no ['Id'] key when I print `message.json` to my screen. Thus, this line does nothing, and will cause the URL to format incorrectly: 
https://github.com/Narcolapser/python-o365/blob/3b4dd7d245b2fa6186ef3c76f6358ea1ba66a15e/O365/attachment.py#L96

Thus, the call fails, which is why False is being returned.

How is ['Id'] supposed to be created within the `json` object?

**Comment by sampellino** [comment] 2016-11-08 18:04
Just another side note, I was able to work around this by reading in the file as a b64 encoded string, and setting it that way.

```
#Read in the file's contents as a base64 encoded string
with open(filepath, "rb") as attachmentFile:
	attachmentB64 = base64.b64encode(attachmentFile.read())

att = O365.Attachment()
att.setBase64(attachmentB64)
att.setName("screenshot.png")
message.attachments.append(att)
```

**Comment by Narcolapser** [comment] 2016-11-08 20:17
The log should live where you script is. Though I just the library so if you are running the latest version you'll need to add the logging configuration back in _before_ you import O365:
```
import logging
logging.basicConfig(filename='o365.log',level=logging.DEBUG)
```

The "ID" issue is actually something I also bumped into recently. Basically the problem is that the attachment class kinda expects that you've some how already sent the message and now want to attach it after the fact. Yea. Problematic. I'm going to see if I can't fix that.

Interesting that such a work around would be a solution. I think something is just a bit wrong in the way the attachment logic works. But that solution makes sense. Can you post a sample of what you were doing before that work around? Assuming that your code looks different from @darryllane.

**Comment by sampellino** [comment] 2016-11-08 20:59
Unfortunately, I already changed it and made many modifications to the file. Mine was exactly the same as @darryllane 's code, except my path was formatted like:

`C:\...\...\...\...\screenshot.png`

So it pretty much the same. Something like:
```
filepath = "C:\\...\\...\\...\\...\\screenshot.png"
m = Message(auth=authenticiation)
att = Attachment(path=filepath)
m.attachments.append(att)
```

**Comment by Narcolapser** [comment] 2016-11-10 14:28
Huh. I tried to do this on one of my servers and got the following message: 

```
Python 2.6.6 (r266:84292, Nov 21 2013, 10:50:32)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from O365 import *
>>> auth = ('Test@address.com','toughnuggets')
>>> m = Message(auth=auth)
>>> att = Attachment(path='./setup.py')
>>> m.attachments.append(att)
>>> m.setRecipients('IRL@address.com')
True
>>> m.setSubject("atty test.")
>>> m.setBody("Worketh?")
>>> m.sendMessage()
/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/lib/python2.6/site-packages/requests-2.11.1-py2.6.egg/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
```

I wonder if you are getting a similar problem? What version of python are you running exactly?

Looking at it a little further, these appear to be just warning. Hmm. Further research is needed!

**Comment by Narcolapser** [comment] 2016-11-10 15:10
Found it. I was using "encodebytes" to do the B64 encoding, but that method isn't available in python 2. Fix coming soon.

**Comment by sampellino** [comment] 2016-11-10 15:13
Great! Glad you found it.

**Comment by Narcolapser** [comment] 2016-11-10 15:19
Alright. Version [0.9.5](https://pypi.python.org/pypi/O365/0.9.5) has the fix in place. update and you should be good. @darryllane, I am assuming that you were having the same problem. If this doesn't fix the issue for you, let me know. But for now I'm marking this as resolved.

**Closed by Narcolapser** 2016-11-10 15:19 UTC
Labels: bug

**Comment by silverstar194** [comment] 2018-01-24 22:25
@sampellino used your workaround to attach. The library still seems to be broken for me.
